### ISSUE TITLE
Not possbile to run on Serveral OS

### ISSUE THREAD

**Issue by GammaPotato** [JGeek00/my-server-status-api#4]
Error OS not Supported on

Windows 11 Pro for Workstations
Version: 22H2

Windows Server 10 Datacenter 2019
Verison: 1809

```
Minimum OS required:
Linux distro based on Ubuntu 20.04 LTS or Debian 10
macOS 11 (Apple Silicon is supported)
Windows 10
```
why it dont work for me?

**Comment by JGeek00** [comment]
Hi. I dropped support for Windows systems a few versions ago do to unreliable data sources and very bad performance (in comparison with Linux and macOS). Also, this software is mainly developed to be used on Linux. When I released it, Windows was supported, and that's why the instructions says that you can use it on Windows, but on later versions I dropped support for Windows but I forgot to remove it from the instructions.

**Comment by GammaPotato** [comment]
why removed support for windows? Windows is the most used OS in the world. if this tool will be easy to use and install it will be usefull for a loot of people. plz add support for Windows back.

**Comment by JGeek00** [comment]
Well... Windows is the most used OS on desktop, this is a server side application. On servers the main OS is Linux. Anyway, the reason why I dropped support for Windows it's just because I didn't have a reliable source of data and the performance was very bad. On Windows a request to get the general status take around 2 seconds (and pumps CPU usage to 100%) while on Linux and macOS that is around 0.3 seconds.
